FROM python:3.13.11-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/
RUN pip install pandas pyarrow
COPY pyproject.toml .python-version uv.lock ./
RUN uv sync --locked
WORKDIR /code
ENV PATH = "/code/.venv/bin:${PATH}"
COPY pipeline-month.py .

ENTRYPOINT  ["python","pipeline-month.py"]